### ISSUE TITLE
Reviewing interests "tagit" results not styled properly on registration

### ISSUE THREAD

**Issue by dalemoore** [pkp/healthSciences#152] opened 2019-06-04 16:29 UTC
When you enter reviewing interests under user/register, there is a search results div that gets added as soon as you type in that field. But it appears at the very bottom of the page, where it will say "No search results." which looks weird appearing after the footer. I am assuming it's supposed to appear directly below the input, or not at all.

**Comment by Vitaliy-1** [comment] 2019-06-06 10:08
Yes, it probably should be hidden. @sssoz can you take a look?

**Comment by sssoz** [comment] 2019-06-14 09:51
@dalemoore - I am trying to reproduce this issue and I’m not able to. 

Can you send me a screenshot?  Here’s what I am seeing: 

![b5b158719320aff555d8f88938f3bcdb](https://user-images.githubusercontent.com/6668406/59500916-45dd2100-8e92-11e9-9488-513fd1726712.gif)

**Comment by dalemoore** [comment] 2019-06-14 12:48
Sure, here you go. We created a completely custom child theme of the Health Sciences theme, but I switched it back to the Health Sciences theme itself to demonstrate/screenshot as I used CSS to manually hide it in the child theme.

![nosearchresults](https://user-images.githubusercontent.com/741846/59510247-d444a900-8e78-11e9-86a6-0c45d2352bfd.jpg)

**Comment by sssoz** [comment] 2019-06-14 13:11
It’s being added in the HTML, but doesn’t appear on the page? I’ve checked in other themes, and I can see that it’s also being added there:  

<img width="758" alt="Screen Shot 2019-06-14 at 14 09 47" src="https://user-images.githubusercontent.com/6668406/59511451-34097700-8eae-11e9-9907-c4e69cf30701.png">

If that’s the issue, don’t think it’s related to the theme - but I’ll keep checking.

**Comment by sssoz** [comment] 2019-06-14 15:30
@dalemoore This is an issue appearing in all other themes -- I’ve moved it to OJS core, if you’d like to follow up on it there: https://github.com/pkp/pkp-lib/issues/4830 

Closing this one here.

**Comment by NateWr** [comment] 2019-08-14 14:24
@sssoz to fix this, you'll need to apply some styles to each theme where it is effected. You can see @thinkbulecount2's solution in the PR here: https://github.com/pkp/ojs/pull/2444/files

**Comment by thinkbulecount2** [comment] 2019-08-16 15:53
[Pull Request](https://github.com/pkp/healthSciences/pull/162) would anyone be able to review? @Vitaliy-1 or @sssoz ?

**Comment by Vitaliy-1** [comment] 2020-06-18 09:37
Looks like resolved, closing.

**Closed by Vitaliy-1** 2020-06-18 09:37 UTC
