### ISSUE TITLE
Archives page is not showing any issues

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#14] opened 2018-02-25 15:22 UTC
Think, topic is self explanatory.

**Comment by NateWr** [comment] 2018-03-06 13:54
Hmm, is it showing "you have not published any issues"? Here's what it should look like:

![selection_073](https://user-images.githubusercontent.com/2306629/37035883-de69904a-2145-11e8-97f8-890cfede8275.png)

**Comment by Vitaliy-1** [comment] 2018-03-06 18:30
Yep. Think the fatal error from PHP log is self-explanatory:
`PHP Fatal error:  Uncaught Error: Call to undefined method IssueDAO::getLocalizedCoverImageUrl()``
(comes from Smarty)

**Comment by NateWr** [comment] 2018-03-07 10:40
That's an interesting one! What's the file/line reference on that error message?

The theme does call getLocalizedCoverImageUrl() [here](https://github.com/pkp/healthSciences/blob/master/templates/frontend/objects/issue_summary.tpl#L15-L19), but that should be `Issue::getLocalizedCoverImageUrl()`, not the DAO.

**Comment by Vitaliy-1** [comment] 2018-03-07 13:55
```
in C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\cache\\t_compile\\cc87c37be02cfb67c21f370fae28834e2716951e^%%91^91C^91C532D2%%issue_summary.tpl.php:7\nStack trace:\n#0 C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\Smarty.class.php(1870): include()\n#1 C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\lib\\pkp\\classes\\template\\PKPTemplateManager.inc.php(419): Smarty->_smarty_include(Array)\n#2 C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\cache\\t_compile\\e3cc64afb84d01d84b42cd0305dc478b9eef9a2d^%%6B^6B5^6B5271FB%%issueArchive.tpl.php(49): PKPTemplateManager->_smarty_include(Array)\n#3 C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\Smarty.class.php(1257): include('C:\\\\xampp2\\\\htdoc...')\n#4 C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\lib\\pkp\\classes\\template\\PKPTemplateManager.inc.php(821): Smarty->fetch('frontend/pages/...', NULL, 'e3cc64afb84d01d...', true)\n#5 C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\ in C:\\xampp2\\htdocs\\ojs-3.1.0-1-theme\\cache\\t_compile\\cc87c37be02cfb67c21f370fae28834e2716951e^%%91^91C^91C532D2%%issue_summary.tpl.php on line 7, referer: http://ojs-3.1.0-1-theme.test/index.php/psp/article/view/86
```
This line in compiled file:
```<?php if ($this->_tpl_vars['issue']->getLocalizedCoverImageUrl()): ?>```

**Comment by Vitaliy-1** [comment] 2018-03-07 14:00
I think it should be:
`{if $issueCover}`

**Comment by Vitaliy-1** [comment] 2018-03-07 14:14
Also, if we have so many methods associated with cover images (8 to be exact), did you consider to make separate `CoverImage` Class? This maybe be true and for article's cover.

**Comment by NateWr** [comment] 2018-03-28 09:56
I was never able to reproduce this issue, and the fact that the error message points to `IssueDAO::getLocalizedCoverImageUrl()` suggests to me that there's something wonky going on with your setup. 

I'm going to close this but if you continue to have issues on a fresh install after 3.1.1 is released let me know and we'll check again.

**Closed by NateWr** 2018-03-28 09:56 UTC

**Comment by Vitaliy-1** [comment] 2018-03-28 10:09
Have you tested it with issues that doen't have a cover image?

**Comment by NateWr** [comment] 2018-03-28 10:14
Yes, and I don't have a problem. What's strange is that this line in the compiled file:

```
$this->_tpl_vars['issue']
```

Should point to an `Issue` object, not a `IssueDAO` object. If it did point to `IssueDAO`, that would be a huge problem that would cause lots of issues for me. But in your error message it appears that it does.

That's why I wonder if there is some kind of template variable override happening in your setup (maybe a custom plugin or code change?) that is overriding the `$issue` template variable there. It seems unlikely but I'm not sure what else could be causing that...

**Comment by Vitaliy-1** [comment] 2018-03-28 13:44
@NateWr 
I have temporarily performed a test install of the theme on my Ubuntu server. OJS 3.1.0-1, PHP 7.1. The problem is the same (Although I haven't looked at the server logs). You can check it by the link:  http://ojsdemo.e-medjournal.com/index.php/oldGregg/issue/archive
I will change the theme back to Old Gregg after few hours.

**Comment by NateWr** [comment] 2018-03-28 14:00
Hi @Vitaliy-1, thanks for the link. It looks like some fatal errors caused some of the other issues, as you've discovered. I'm still not sure what cause the `Issue` -> `IssueDAO` swap, but do paste in the full error messages when you see them. That might help us track down the issue.

**Comment by Vitaliy-1** [comment] 2018-03-29 07:41
`PHP Fatal error:  Uncaught Error: Call to undefined method IssueDAO::getLocalizedCoverImageUrl() in /var/www/.../cache/t_compile/cc87c37be02cfb67c21f370fae28834e2716951e^%%91^91C^91C532D2%%issue_summary.tpl.php:7\nStack trace:\n#0 /var/www/.../lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1870): include()\n#1 /var/www/.../lib/pkp/classes/template/PKPTemplateManager.inc.php(416): Smarty->_smarty_include(Array)\n#2 /var/www/.../cache/t_compile/e3cc64afb84d01d84b42cd0305dc478b9eef9a2d^%%6B^6B5^6B5271FB%%issueArchive.tpl.php(49): PKPTemplateManager->_smarty_include(Array)\n#3 /var/www/.../lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1257): include('/var/www/...')\n#4 /var/.../lib/pkp/classes/template/PKPTemplateManager.inc.php(793): Smarty->fetch('frontend/pages/...', NULL, 'e3cc64afb84d01d...', true)\n#5 /var/www/ojsdemo.e-me in /var/www/.../cache/t_compile/cc87c37be02cfb67c21f370fae28834e2716951e^%%91^91C^91C532D2%%issue_summary.tpl.php on line 7, referer: http://ojsdemo.e-medjournal.com/index.php/oldGregg/login?source=%2Findex.php%2FoldGregg%2Fsubmissions`

**Comment by Vitaliy-1** [comment] 2018-03-29 07:44
PHP Fatal error:  Uncaught Error: Call to undefined method IssueDAO::getLocalizedCoverImageUrl() in /var/www/.../cache/t_compile/cc87c37be02cfb67c21f370fae28834e2716951e^%%91^91C^91C532D2%%issue_summary.tpl.php:7\nStack trace:\n#0 /var/www/.../lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1870): include()\n#1 /var/www/.../lib/pkp/classes/template/PKPTemplateManager.inc.php(416): Smarty->_smarty_include(Array)\n#2 /var/www/.../cache/t_compile/e3cc64afb84d01d84b42cd0305dc478b9eef9a2d^%%6B^6B5^6B5271FB%%issueArchive.tpl.php(49): PKPTemplateManager->_smarty_include(Array)\n#3 /var/www/.../lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1257): include('/var/www/...')\n#4 /var/www/.../lib/pkp/classes/template/PKPTemplateManager.inc.php(793): Smarty->fetch('frontend/pages/...', NULL, 'e3cc64afb84d01d...', true)\n#5 /var/www/... in /var/www/.../cache/t_compile/cc87c37be02cfb67c21f370fae28834e2716951e^%%91^91C^91C532D2%%issue_summary.tpl.php on line 7, referer: http://ojsdemo.e-medjournal.com/index.php/oldGregg

**Comment by Vitaliy-1** [comment] 2018-03-29 07:49
And for article detail page:

`PHP Fatal error:  Uncaught Error: Call to a member function getCount() on null in /var/www/.../cache/t_compile/cc87c37be02cfb67c21f370fae28834e2716951e^%%17^178^1786CABF%%article_details.tpl.php:368\nStack trace:\n#0 /var/www/.../lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1870): include()\n#1 /var/www/.../lib/pkp/classes/template/PKPTemplateManager.inc.php(416): Smarty->_smarty_include(Array)\n#2 /var/www/o.../cache/t_compile/93b4f13326abf2c920de729fdcdace1580d9bcb7^%%2D^2D7^2D7EC92F%%article.tpl.php(13): PKPTemplateManager->_smarty_include(Array)\n#3 /var/www/.../lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1257): include('/var/www/ojsdem...')\n#4 /var/www/.../lib/pkp/classes/template/PKPTemplateManager.inc.php(793): Smarty->fetch('frontend/pages/...', NULL, '93b4f13326abf2c...', true)\n#5 /var/www/ojsdemo.e-medjournal.com/site_h in /var/www/.../cache/t_compile/cc87c37be02cfb67c21f370fae28834e2716951e^%%17^178^1786CABF%%article_details.tpl.php on line 368, referer: http://ojsdemo.e-medjournal.com/index.php/oldGregg/issue/view/2`

**Comment by Vitaliy-1** [comment] 2018-03-29 07:58
@NateWr 
For the archive page, there are 2 issues and both of them have a cover image. But I remember that deleted one or both cover images at some time point. Can you check it on your test installation?

**Comment by NateWr** [comment] 2018-03-29 14:34
Hi @Vitaliy-1,

Hmm, the `IssueDAO` error in `issue_summary.tpl` still doesn't make any sense to me, but the `getCount()` error in `article_details.tpl` is probably because you're on 3.0.1-1. I don't think the `CitationDAO` is available in that version.

**Comment by Vitaliy-1** [comment] 2018-04-01 18:28
Hi @NateWr 
I have recently installed a fresh OJS 3.1.0-1 and can say that the problem with archive page is there from the start without any published issues. Also, I have seen somewhere on the internet another OJS installation with Health Sciences theme with the same problem. 
Ahh, here it is:
http://www.ijohsr.com/ojs/index.php/ijohsr/issue/archive

**Comment by NateWr** [comment] 2018-04-02 10:34
@Vitaliy-1, I just can't track down anywhere that `IssueDAO::getLocalizedCoverImageUrl()` is called. The line in the template file where this error is occurring should _never_ be a `IssueDAO`. Without steps to reproduce, I can't debug any further.

**Comment by NateWr** [comment] 2018-04-02 10:35
I should also say, though, that the theme is never intended to work with OJS 3.1.0-1. It requires the `master` branch and, eventually, 3.1.1.

That doesn't seem to address this specific issue, but it's still possible, and we won't be debuggingn any issues specific to OJS 3.1.0-1.

**Comment by Vitaliy-1** [comment] 2018-05-11 18:48
Hi @EduardoOsquel 
Sorry for the delay. First of all, can you open this issue on oldGregg theme page if it is related only to that theme? 
Secondly, can you point that line (with the error, it is in compiled PHP files, cache directory) there? 
Thirdly, did the upgrade process passed successfully and did you cleared cache folder after it?

**Comment by EduardoOsquel** [comment] 2018-05-11 19:09
Thanks @Vitaliy-1 for your request... I find a section code (posted by yourself) that help me to solve this trouble by modifing to .tpl files, greetings my friend
