### ISSUE TITLE
Problems with dropdown buttons

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#15] opened 2018-02-25 15:26 UTC
Sometimes when clicking on the dropdown menu button inside header, instead of showing dropdown menu I'm getting the redirect by the dropdown button's link.

**Comment by NateWr** [comment] 2018-03-06 13:46
Hmm, it sounds like there are some JS issues happening. I wonder if this is related to the issues you're having with #12. Do you see any messages in the console?

**Comment by Vitaliy-1** [comment] 2018-03-06 18:25
Chrome console is empty. Firefox shows warnings from Bootstrap on page loading (but not on click); they seem to be not related to this issue.

**Comment by NateWr** [comment] 2018-03-07 10:37
Can you share the Bootstrap warnings? I'm not able to reproduce this and haven't had any other reports of an issue, so any clue might help.

**Comment by Vitaliy-1** [comment] 2018-03-07 13:46
To be more precise, when clicking for the FIRST time on the dropdown in the header I can be redirected by its link. I didn't notice such behavior with Bootstrap's dropdown buttons. So, if you are using Bootstrap here, it's quite strange. 
About the errors in Firefox, I see many of these:
```
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.
bootstrap.min.css:6:839
Unrecognized at-rule or error parsing at-rule ‘@-ms-viewport’.
bootstrap.min.css:6:952
Error in parsing value for ‘outline’.  Declaration dropped.
bootstrap.min.css:6:3100
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:3981
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:4133
Unknown pseudo-class or pseudo-element ‘-webkit-file-upload-button’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:4229
Error in parsing value for ‘word-break’.  Declaration dropped.
bootstrap.min.css:6:5972
Error in parsing value for ‘display’.  Declaration dropped.
bootstrap.min.css:6:6748
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:24834
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:25028
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:25149
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:25209
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector.
bootstrap.min.css:6:25490
Error in parsing value for ‘display’.  Declaration dropped.
```

**Comment by NateWr** [comment] 2018-03-28 09:55
We were unable to reproduce this ourselves, so I'm closing for now. I'll certainly re-open if we receive any more reports.

**Closed by NateWr** 2018-03-28 09:55 UTC

**Comment by Vitaliy-1** [comment] 2018-03-28 13:57
I was able to reproduce the problem on Ubuntu server. Actually, when I clicked on Archive page or Article landing page the next click on About button referred me to the about journal page. This was probably happening because of an error upon compiling Smarty templates for those pages, so javascript just didn't load...
