### ISSUE TITLE
HowToCite dropdown is not working on article detail page

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#12] opened 2018-02-25 15:16 UTC
Dropdown on "More Citation Formats` Button is not working. No errors in the browser's console. But maybe it is due to my own modifications of the plugin (I'm testing on the clone of our journal). So needs additional check.

**Comment by NateWr** [comment] 2018-03-06 13:41
I'm not able to reproduce this myself. Can you share the browser and OS you're using?

(I did discover a couple of other issues in the process, though, so thanks!)

**Comment by Vitaliy-1** [comment] 2018-03-06 18:33
My development machine stands on Windows 10. Usually, I check the errors in a latest stable release of Google Chrome and Firefox. But this specific issue comes only from Chrome.

**Comment by NateWr** [comment] 2018-03-07 10:41
I'll try to find a team member with Windows 10 who can try to reproduce this and the other issue.

**Comment by Vitaliy-1** [comment] 2018-03-07 13:38
Ahh, sorry, the previous answer was related to issue #15. Actually, Dropdown on article detail page (from how to cite plugin) isn't working in Chrome AND Firefox in my case.

**Comment by NateWr** [comment] 2018-03-28 09:55
We were unable to reproduce this ourselves, so I'm closing for now. I'll certainly re-open if we receive any more reports.

**Closed by NateWr** 2018-03-28 09:55 UTC

**Comment by Vitaliy-1** [comment] 2018-03-28 13:50
Ahh. The problem is because of the error upon template compiling. You can see it at the link (it will be available for several hours): http://ojsdemo.e-medjournal.com/index.php/oldGregg/article/view/5
The footer there is not downloading, I will tell you more when view the logs.
